### ISSUE TITLE
Internal server error when breaking wheat crops

### ISSUE THREAD

**Issue by noteHaze** [RhysB/Project-Poseidon#94]
When breaking wheat crops, no seeds are dropped, and there's a 1/3 chance of an Internal server error happening.

Error log:
```
00:57:55 [WARNING] Failed to handle packet: java.lang.UnsupportedOperationException
java.lang.UnsupportedOperationException
        at java.util.AbstractList.add(AbstractList.java:148)
        at java.util.AbstractList.add(AbstractList.java:108)
        at net.minecraft.server.BlockCrops.getDrops(BlockCrops.java:97)
        at net.minecraft.server.Block.dropNaturally(Block.java:313)
        at net.minecraft.server.Block.g(Block.java:302)
        at net.minecraft.server.Block.a(Block.java:511)
        at net.minecraft.server.ItemInWorldManager.c(ItemInWorldManager.java:189)
        at net.minecraft.server.ItemInWorldManager.dig(ItemInWorldManager.java:104)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:548)
        at net.minecraft.server.Packet14BlockDig.a(Packet14BlockDig.java:34)
        at net.minecraft.server.NetworkManager.b(NetworkManager.java:290)
        at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:131)
        at net.minecraft.server.NetworkListenThread.a(NetworkListenThread.java:72)
        at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:561)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:438)
        at net.minecraft.server.ThreadServerApplication.run(ThreadServerApplication.java:13)
```

**Comment by RhysB** [comment]
It's likely an issue with https://github.com/RhysB/Project-Poseidon/commit/3dcd51c5d10e12e825a949b1894fbfac23c7b526 (@Meep3692)

I have reverted the change. Could you try downloading the latest version of Poseidon and see if the issue continues?

**Comment by noteHaze** [comment]
Looks fixed on my end, crops can drop seeds without any crashing.

**Comment by W-i-n-7** [comment]
i was having the same issue and now the new build fixed it

**Comment by moderatorman** [comment]
Appears to be resolved, closing.
